version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=saude_digital
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: ./saude_digital
    ports:
      - "8000:8000"
    volumes:
      - ./saude_digital:/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=saude_digital
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123
    depends_on:
      - db

  frontend:
    build: ./Front_Saude_Digital
    ports:
      - "5173:5173"
    volumes:
      - ./Front_Saude_Digital:/app
    depends_on:
      - web

volumes:
  db_data:
