# Generated by Django 3.2 on 2024-10-02 17:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('codigo_corretor', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('clientes_vinculados', models.PositiveIntegerField(default=0)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_corretor/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_postadas', to='app_saude_digital.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(help_text='Valores entre 1 e 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_feedback', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_saude_digital.cliente')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_saude_digital.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteCorretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_associacao', models.DateField()),
                ('status_associacao', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_saude_digital.cliente')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_saude_digital.corretor')),
            ],
            options={
                'unique_together': {('cliente', 'corretor')},
            },
        ),
        migrations.CreateModel(
            name='PlanoDeSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_especialidade', models.CharField(max_length=100)),
                ('corretor', models.ForeignKey(on_delete=models.CASCADE, related_name='planos', to='app_name.Corretor')),
            ],
        ),
    ]
