# Generated by Django 3.2 on 2024-10-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_saude_digital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corretor',
            old_name='codigo_coretor',
            new_name='codigo_corretor',
        ),
    ]
