# Generated by Django 3.2 on 2024-10-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saude_digital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcliente',
            name='data_feedback',
            field=models.DateField(auto_now_add=True),
        ),
    ]
