# Generated by Django 5.1.1 on 2024-12-13 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saude_digital', '0002_alter_feedbackcliente_data_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CorretorPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_saude_digital.corretor')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_saude_digital.plano')),
            ],
            options={
                'unique_together': {('corretor', 'plano')},
            },
        ),
        migrations.DeleteModel(
            name='PlanoDeSaude',
        ),
    ]
