# Generated by Django 4.2.17 on 2024-12-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saude_digital', '0002_alter_feedbackcliente_data_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='corretor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
