# Generated by Django 2.2.12 on 2024-09-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saude_digital', '0003_usuario_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('codigo', models.IntegerField(null=True)),
            ],
        ),
    ]
