# Generated by Django 4.2.17 on 2024-12-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saude_digital', '0003_corretor_latitude_corretor_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
    ]
