# Generated by Django 5.1.1 on 2024-12-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saude_digital', '0003_plano_corretorplano_delete_planodesaude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='preco_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
