# Generated by Django 2.2.12 on 2024-09-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_saude_digital', '0004_corretor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Cliente',
        ),
    ]
